identifier = "com.luoluoqixi.lonanote"

[app]

[[app.windows]]
label = "main"
tabbingIdentifier = "main"
title = "lonanote"
titleBarStyle = "Transparent"
resizable = true
fullscreen = false
width = 1024
height = 576
