if(DEFINED LONANOTE_ANDROID_TOOLCHAIN_WRAPPER_INCLUDED)
  return()
endif()
set(LONANOTE_ANDROID_TOOLCHAIN_WRAPPER_INCLUDED TRUE)

if(NOT DEFINED LONANOTE_CMAKE_OBJECT_PATH_MAX)
  set(LONANOTE_CMAKE_OBJECT_PATH_MAX 1024)
endif()

if(DEFINED CMAKE_TRY_COMPILE_PLATFORM_VARIABLES)
  list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    LONANOTE_CMAKE_OBJECT_PATH_MAX
    LONANOTE_ANDROID_ORIGINAL_TOOLCHAIN_FILE
  )
else()
  set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    LONANOTE_CMAKE_OBJECT_PATH_MAX
    LONANOTE_ANDROID_ORIGINAL_TOOLCHAIN_FILE
  )
endif()
list(REMOVE_DUPLICATES CMAKE_TRY_COMPILE_PLATFORM_VARIABLES)

set(CMAKE_OBJECT_PATH_MAX "${LONANOTE_CMAKE_OBJECT_PATH_MAX}" CACHE STRING "LonaNote object path max" FORCE)

if(DEFINED LONANOTE_ANDROID_ORIGINAL_TOOLCHAIN_FILE)
  set(_lonanote_android_original_toolchain "${LONANOTE_ANDROID_ORIGINAL_TOOLCHAIN_FILE}")
elseif(DEFINED ANDROID_NDK)
  set(_lonanote_android_original_toolchain "${ANDROID_NDK}/build/cmake/android.toolchain.cmake")
elseif(DEFINED CMAKE_ANDROID_NDK)
  set(_lonanote_android_original_toolchain "${CMAKE_ANDROID_NDK}/build/cmake/android.toolchain.cmake")
else()
  message(FATAL_ERROR "Could not resolve Android NDK for toolchain wrapper")
endif()

include("${_lonanote_android_original_toolchain}")
