

[workspace]
members = ["icon_gen"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.1"
authors = ["luoluoqixi"]
repository = "https://github.com/luoluoqixi/lonanote"
license = ""

[workspace.dependencies]
anyhow = "1.0.98"
log = "0.4.27"
fern = "0.7.1"
chrono = "0.4.40"
image = "0.25.6"
icns = "0.3.1"
