// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::lonanote_rust_module_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::lonanoterustmodule::bridging")]
pub mod bridging {
    extern "Rust" {
        type LonanoteRustModule;

        #[cxx_name = "createLonanoteRustModule"]
        fn create_lonanote_rust_module(id: usize, data_path: &str) -> Box<LonanoteRustModule>;

        #[cxx_name = "add"]
        fn lonanote_rust_module_add(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "divide"]
        fn lonanote_rust_module_divide(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "multiply"]
        fn lonanote_rust_module_multiply(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "subtract"]
        fn lonanote_rust_module_subtract(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64>;
    }
}

fn create_lonanote_rust_module(id: usize, data_path: &str) -> Box<LonanoteRustModule> {
    let ctx = Context::new(id, data_path);
    Box::new(LonanoteRustModule::new(ctx))
}

fn lonanote_rust_module_add(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.add(a, b);
        ret
    })
}

fn lonanote_rust_module_divide(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.divide(a, b);
        ret
    })
}

fn lonanote_rust_module_multiply(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.multiply(a, b);
        ret
    })
}

fn lonanote_rust_module_subtract(it_: &mut LonanoteRustModule, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.subtract(a, b);
        ret
    })
}


