// Auto generated by Craby. DO NOT EDIT.
// Hash: 4c553ec5e6e04db5
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait LonanoteRustModuleSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn emit(&self, signal_name: LonanoteRustModuleSignal) {
        let manager = crate::ffi::bridging::get_signal_manager();
        match signal_name {
            LonanoteRustModuleSignal::OnCallbackRequest(data) => {
                let signal = Box::new(LonanoteRustModuleSignal::OnCallbackRequest(data));
                let signal_ptr = Box::into_raw(signal);
                unsafe {
                    manager.emit(self.id(), "onCallbackRequest", signal_ptr);
                }
            }
        }
    }
    fn clear_callback_function(&mut self) -> Promise<Void>;
    fn get_command_async_keys(&mut self) -> Array<String>;
    fn get_command_async_length(&mut self) -> Number;
    fn get_command_callback_keys(&mut self) -> Array<String>;
    fn get_command_callback_length(&mut self) -> Number;
    fn get_command_keys(&mut self) -> Array<String>;
    fn get_command_length(&mut self) -> Number;
    fn init(&mut self) -> Nullable<String>;
    fn invoke(&mut self, command: &str, args: Nullable<String>) -> Nullable<String>;
    fn invoke_async(&mut self, command: &str, args: Nullable<String>) -> Promise<Nullable<String>>;
    fn reg_callback_function(&mut self, key: &str) -> Promise<Void>;
    fn reject_callback(&mut self, id: &str, error: &str) -> Void;
    fn resolve_callback(&mut self, id: &str, result: Nullable<String>) -> Void;
    fn unreg_callback_function(&mut self, key: &str) -> Promise<Void>;
}

pub enum LonanoteRustModuleSignal {
    OnCallbackRequest(CallbackRequest),
}

impl Default for NullableString {
    fn default() -> Self {
        NullableString {
            null: true,
            val: String::default(),
        }
    }
}

impl From<NullableString> for Nullable<String> {
    fn from(val: NullableString) -> Self {
        Nullable::new(if val.null { None } else { Some(val.val) })
    }
}

impl From<Nullable<String>> for NullableString {
    fn from(val: Nullable<String>) -> Self {
        let val = val.into_value();
        let null = val.is_none();
        NullableString {
            val: val.unwrap_or(String::default()),
            null,
        }
    }
}

impl Default for CallbackRequest {
    fn default() -> Self {
        CallbackRequest {
            id: String::default(),
            key: String::default(),
            args: NullableString::default(),
        }
    }
}
