// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::lonanote_ui_core_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::lonanoteuicore::bridging")]
pub mod bridging {
    extern "Rust" {
        type LonanoteUiCore;

        #[cxx_name = "createLonanoteUiCore"]
        fn create_lonanote_ui_core(id: usize, data_path: &str) -> Box<LonanoteUiCore>;

        #[cxx_name = "add"]
        fn lonanote_ui_core_add(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "divide"]
        fn lonanote_ui_core_divide(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "multiply"]
        fn lonanote_ui_core_multiply(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64>;

        #[cxx_name = "subtract"]
        fn lonanote_ui_core_subtract(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64>;
    }
}

fn create_lonanote_ui_core(id: usize, data_path: &str) -> Box<LonanoteUiCore> {
    let ctx = Context::new(id, data_path);
    Box::new(LonanoteUiCore::new(ctx))
}

fn lonanote_ui_core_add(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.add(a, b);
        ret
    })
}

fn lonanote_ui_core_divide(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.divide(a, b);
        ret
    })
}

fn lonanote_ui_core_multiply(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.multiply(a, b);
        ret
    })
}

fn lonanote_ui_core_subtract(it_: &mut LonanoteUiCore, a: f64, b: f64) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.subtract(a, b);
        ret
    })
}


