// Auto generated by Craby. DO NOT EDIT.
// Hash: bc8cb0883f4ea77c
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait LonanoteUiCoreSpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn add(&mut self, a: Number, b: Number) -> Number;
    fn divide(&mut self, a: Number, b: Number) -> Number;
    fn multiply(&mut self, a: Number, b: Number) -> Number;
    fn subtract(&mut self, a: Number, b: Number) -> Number;
}
