// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_invoke_result`

String? init() => RustLib.instance.api.crateApiCommandInit();

String? invoke({required String key, String? args}) =>
    RustLib.instance.api.crateApiCommandInvoke(key: key, args: args);

List<String> getCommandKeys() =>
    RustLib.instance.api.crateApiCommandGetCommandKeys();

BigInt getCommandLen() => RustLib.instance.api.crateApiCommandGetCommandLen();

Future<String?> invokeAsync({required String key, String? args}) =>
    RustLib.instance.api.crateApiCommandInvokeAsync(key: key, args: args);

List<String> getCommandAsyncKeys() =>
    RustLib.instance.api.crateApiCommandGetCommandAsyncKeys();

BigInt getCommandAsyncLen() =>
    RustLib.instance.api.crateApiCommandGetCommandAsyncLen();

void regDartFunction({
  required String key,
  required FutureOr<String?> Function(String?) callback,
}) => RustLib.instance.api.crateApiCommandRegDartFunction(
  key: key,
  callback: callback,
);

void unregDartFunction({required String key}) =>
    RustLib.instance.api.crateApiCommandUnregDartFunction(key: key);

void clearDartFunction() =>
    RustLib.instance.api.crateApiCommandClearDartFunction();

List<String> getCommandDartKeys() =>
    RustLib.instance.api.crateApiCommandGetCommandDartKeys();

BigInt getCommandDartLen() =>
    RustLib.instance.api.crateApiCommandGetCommandDartLen();
