// Auto generated by Craby. DO NOT EDIT.
#include "CxxLonanoteRustModuleModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace lonanoterustmodule {
namespace modules {

std::string CxxLonanoteRustModuleModule::dataPath = std::string();

CxxLonanoteRustModuleModule::CxxLonanoteRustModuleModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxLonanoteRustModuleModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::lonanoterustmodule::bridging::LonanoteRustModule>(
    craby::lonanoterustmodule::bridging::createLonanoteRustModule(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::lonanoterustmodule::bridging::LonanoteRustModule *ptr) { rust::Box<craby::lonanoterustmodule::bridging::LonanoteRustModule>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::lonanoterustmodule::utils::ThreadPool>(10);
  methodMap_["add"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::add};
  methodMap_["divide"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::divide};
  methodMap_["multiply"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::multiply};
  methodMap_["subtract"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::subtract};
}

CxxLonanoteRustModuleModule::~CxxLonanoteRustModuleModule() {
  invalidate();
}

void CxxLonanoteRustModuleModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxLonanoteRustModuleModule::add(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoterustmodule::bridging::add(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::divide(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoterustmodule::bridging::divide(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::multiply(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoterustmodule::bridging::multiply(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::subtract(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoterustmodule::bridging::subtract(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace lonanoterustmodule
} // namespace craby
