// Auto generated by Craby. DO NOT EDIT.
#include "CxxLonanoteRustModuleModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace lonanoterustmodule {
namespace modules {

std::string CxxLonanoteRustModuleModule::dataPath = std::string();

CxxLonanoteRustModuleModule::CxxLonanoteRustModuleModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxLonanoteRustModuleModule::kModuleName, jsInvoker) {
  uintptr_t id = reinterpret_cast<uintptr_t>(this);
  auto& manager = craby::lonanoterustmodule::signals::SignalManager::getInstance();
  manager.registerDelegate(id,
    [this](const std::string& name, void* signal) {
      this->emit(name, reinterpret_cast<bridging::LonanoteRustModuleSignal*>(signal));
    }
  );
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::lonanoterustmodule::bridging::LonanoteRustModule>(
    craby::lonanoterustmodule::bridging::createLonanoteRustModule(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::lonanoterustmodule::bridging::LonanoteRustModule *ptr) { rust::Box<craby::lonanoterustmodule::bridging::LonanoteRustModule>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::lonanoterustmodule::utils::ThreadPool>(10);
  methodMap_["clearCallbackFunction"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::clearCallbackFunction};
  methodMap_["getCommandAsyncKeys"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::getCommandAsyncKeys};
  methodMap_["getCommandAsyncLength"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::getCommandAsyncLength};
  methodMap_["getCommandCallbackKeys"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::getCommandCallbackKeys};
  methodMap_["getCommandCallbackLength"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::getCommandCallbackLength};
  methodMap_["getCommandKeys"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::getCommandKeys};
  methodMap_["getCommandLength"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::getCommandLength};
  methodMap_["init"] = MethodMetadata{0, &CxxLonanoteRustModuleModule::init};
  methodMap_["invoke"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::invoke};
  methodMap_["invokeAsync"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::invokeAsync};
  methodMap_["regCallbackFunction"] = MethodMetadata{1, &CxxLonanoteRustModuleModule::regCallbackFunction};
  methodMap_["rejectCallback"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::rejectCallback};
  methodMap_["resolveCallback"] = MethodMetadata{2, &CxxLonanoteRustModuleModule::resolveCallback};
  methodMap_["unregCallbackFunction"] = MethodMetadata{1, &CxxLonanoteRustModuleModule::unregCallbackFunction};
  methodMap_["onCallbackRequest"] = MethodMetadata{1, &CxxLonanoteRustModuleModule::onCallbackRequest};
}

CxxLonanoteRustModuleModule::~CxxLonanoteRustModuleModule() {
  invalidate();
}

void CxxLonanoteRustModuleModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // Unregister from signal manager
  uintptr_t id = reinterpret_cast<uintptr_t>(this);
  auto& manager = craby::lonanoterustmodule::signals::SignalManager::getInstance();
  manager.unregisterDelegate(id);

  // Shutdown thread pool
  threadPool_->shutdown();
}

void CxxLonanoteRustModuleModule::emit(std::string name, bridging::LonanoteRustModuleSignal* signal) {
  std::vector<std::shared_ptr<facebook::jsi::Function>> listeners;
  {
    std::lock_guard<std::mutex> lock(listenersMutex_);
    auto it = listenersMap_.find(name);
    if (it != listenersMap_.end()) {
      for (auto &[_, listener] : it->second) {
        listeners.push_back(listener);
      }
    }
  }

  // Prepare payload: extract from signal or use undefined
  auto payloadPtr = std::make_shared<facebook::jsi::Value>();
  
  if (signal == nullptr) {
    *payloadPtr = facebook::jsi::Value::undefined();
  } else {
    // Use shared_ptr to manage signal lifetime across async callbacks
    auto signalPtr = std::shared_ptr<bridging::LonanoteRustModuleSignal>(
      signal,
      [](bridging::LonanoteRustModuleSignal* ptr) {
        // Use Rust FFI function to drop signal memory
        if (ptr != nullptr) {
          craby::lonanoterustmodule::bridging::drop_signal(ptr);
        }
      }
    );

    // Extract payload using FFI function and convert to jsi::Value
    // We'll need to capture signalPtr in the lambda
    for (auto& listener : listeners) {
      try {
        callInvoker_->invokeAsync([listener, signalPtr, name](jsi::Runtime &rt) {
          jsi::Value data = jsi::Value::undefined();
          if (name == "onCallbackRequest") {
            auto payload = craby::lonanoterustmodule::bridging::get_on_callback_request_payload(*signalPtr);
            data = react::bridging::toJs(rt, payload);
          }
          listener->call(rt, data);
        });
      } catch (const std::exception& err) {
        // Noop
      }
    }
    return;
  }

  for (auto& listener : listeners) {
    try {
      callInvoker_->invokeAsync([listener, payloadPtr](jsi::Runtime &rt) {
        try {
          listener->call(rt, *payloadPtr);
        } catch (const jsi::JSError &err) {
          throw err;
        } catch (const std::exception &err) {
          throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
        }
      });
    } catch (const std::exception& err) {
      // Noop
    }
  }
}

jsi::Value CxxLonanoteRustModuleModule::clearCallbackFunction(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    react::AsyncPromise<std::monostate> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise]() mutable {
      try {
        craby::lonanoterustmodule::bridging::clearCallbackFunction(*it_);
        promise.resolve(std::monostate{});
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::lonanoterustmodule::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::getCommandAsyncKeys(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::lonanoterustmodule::bridging::getCommandAsyncKeys(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::getCommandAsyncLength(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::lonanoterustmodule::bridging::getCommandAsyncLength(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::getCommandCallbackKeys(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::lonanoterustmodule::bridging::getCommandCallbackKeys(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::getCommandCallbackLength(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::lonanoterustmodule::bridging::getCommandCallbackLength(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::getCommandKeys(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::lonanoterustmodule::bridging::getCommandKeys(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::getCommandLength(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::lonanoterustmodule::bridging::getCommandLength(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::init(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::lonanoterustmodule::bridging::init(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::invoke(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1 = react::bridging::fromJs<craby::lonanoterustmodule::bridging::NullableString>(rt, args[1], callInvoker);
    auto ret = craby::lonanoterustmodule::bridging::invoke(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::invokeAsync(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg1 = react::bridging::fromJs<craby::lonanoterustmodule::bridging::NullableString>(rt, args[1], callInvoker);
    react::AsyncPromise<craby::lonanoterustmodule::bridging::NullableString> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0$raw, arg1]() mutable {
      try {
        auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
        auto ret = craby::lonanoterustmodule::bridging::invokeAsync(*it_, arg0, arg1);
        promise.resolve(ret);
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::lonanoterustmodule::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::regCallbackFunction(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    react::AsyncPromise<std::monostate> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0$raw]() mutable {
      try {
        auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
        craby::lonanoterustmodule::bridging::regCallbackFunction(*it_, arg0);
        promise.resolve(std::monostate{});
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::lonanoterustmodule::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::rejectCallback(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    craby::lonanoterustmodule::bridging::rejectCallback(*it_, arg0, arg1);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::resolveCallback(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1 = react::bridging::fromJs<craby::lonanoterustmodule::bridging::NullableString>(rt, args[1], callInvoker);
    craby::lonanoterustmodule::bridging::resolveCallback(*it_, arg0, arg1);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::unregCallbackFunction(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    react::AsyncPromise<std::monostate> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0$raw]() mutable {
      try {
        auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
        craby::lonanoterustmodule::bridging::unregCallbackFunction(*it_, arg0);
        promise.resolve(std::monostate{});
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::lonanoterustmodule::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteRustModuleModule::onCallbackRequest(jsi::Runtime &rt,
                      react::TurboModule &turboModule,
                      const jsi::Value args[],
                      size_t count) {
  auto &thisModule = static_cast<CxxLonanoteRustModuleModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto callback = args[0].asObject(rt).asFunction(rt);
    auto callbackRef = std::make_shared<jsi::Function>(std::move(callback));
    auto id = thisModule.nextListenerId_.fetch_add(1);
    auto name = "onCallbackRequest";

    if (thisModule.listenersMap_.find(name) == thisModule.listenersMap_.end()) {
      thisModule.listenersMap_[name] = std::unordered_map<size_t, std::shared_ptr<facebook::jsi::Function>>();
    }

    {
      std::lock_guard<std::mutex> lock(thisModule.listenersMutex_);
      thisModule.listenersMap_[name].emplace(id, callbackRef);
    }

    auto modulePtr = &thisModule;
    auto cleanup = [modulePtr, name, id] {
      std::lock_guard<std::mutex> lock(modulePtr->listenersMutex_);
      auto eventMap = modulePtr->listenersMap_.find(name);
      if (eventMap != modulePtr->listenersMap_.end()) {
        auto it = eventMap->second.find(id);
        if (it != eventMap->second.end()) {
          eventMap->second.erase(it);
        }
      }
      return jsi::Value::undefined();
    };

    return jsi::Function::createFromHostFunction(
      rt,
      jsi::PropNameID::forAscii(rt, "cleanup"),
      0,
      [cleanup](jsi::Runtime& rt, const jsi::Value&, const jsi::Value*, size_t) -> jsi::Value {
        return cleanup();
      }
    );
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoterustmodule::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace lonanoterustmodule
} // namespace craby
