/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function init(): string | null
export declare function invoke(key: string, args?: string | undefined | null): string | null
export declare function getCommandKeys(): Array<string>
export declare function getCommandLen(): bigint
export declare function invokeAsync(key: string, args?: string | undefined | null): Promise<string | null>
export declare function getCommandAsyncKeys(): Array<string>
export declare function getCommandAsyncLen(): bigint
export declare function regJsFunction(key: string, callback: (args: string | null | undefined) => Promise<string | null | undefined>): void
export declare function unregJsFunction(key: string): void
export declare function clearJsFunction(): void
export declare function getCommandJsKeys(): Array<string>
export declare function getCommandJsLen(): bigint
