export interface UnifiedStore {
  filePath: (storeKey: string) => Promise<string | undefined>;
  filePathSync: (storeKey: string) => string | undefined;
  fileName: (storeKey: string) => Promise<string | undefined>;
  fileNameSync: (storeKey: string) => string | undefined;
  reload: (storeKey: string) => Promise<void>;
  reloadSync: (storeKey: string) => void;
  save: (storeKey: string) => Promise<void>;
  saveSync: (storeKey: string) => void;
  clear: (storeKey: string) => Promise<void>;
  clearSync: (storeKey: string) => void;
  delete: (storeKey: string, key: string) => Promise<boolean>;
  deleteSync: (storeKey: string, key: string) => boolean;
  has: (storeKey: string, key: string) => Promise<boolean>;
  hasSync: (storeKey: string, key: string) => boolean;
  get: <T = unknown>(storeKey: string, key: string) => Promise<T | undefined>;
  getSync: <T = unknown>(storeKey: string, key: string) => T | undefined;
  set: (storeKey: string, key: string, val: unknown) => Promise<void>;
  setSync: (storeKey: string, key: string, val: unknown) => void;
  keys: (storeKey: string) => Promise<string[]>;
  keysSync: (storeKey: string) => string[];
  values: <T = unknown>(storeKey: string) => Promise<T[]>;
  valuesSync: <T = unknown>(storeKey: string) => T[];
  len: (storeKey: string) => Promise<number>;
  lenSync: (storeKey: string) => number;
  isEmpty: (storeKey: string) => Promise<boolean>;
  isEmptySync: (storeKey: string) => boolean;
  all: <T = unknown>(storeKey: string) => Promise<Record<string, T>>;
  allSync: <T = unknown>(storeKey: string) => Record<string, T>;
  commonFilePath: () => Promise<string | undefined>;
  commonFilePathSync: () => string | undefined;
  commonFileName: () => Promise<string | undefined>;
  commonFileNameSync: () => string | undefined;
  commonReload: () => Promise<void>;
  commonReloadSync: () => void;
  commonSave: () => Promise<void>;
  commonSaveSync: () => void;
  commonClear: () => Promise<void>;
  commonClearSync: () => void;
  commonDelete: (key: string) => Promise<boolean>;
  commonDeleteSync: (key: string) => boolean;
  commonHas: (key: string) => Promise<boolean>;
  commonHasSync: (key: string) => boolean;
  commonGet: <T = unknown>(key: string) => Promise<T | undefined>;
  commonGetSync: <T = unknown>(key: string) => T | undefined;
  commonSet: (key: string, val: unknown) => Promise<void>;
  commonSetSync: (key: string, val: unknown) => void;
  commonKeys: () => Promise<string[]>;
  commonKeysSync: () => string[];
  commonValues: <T = unknown>() => Promise<T[]>;
  commonValuesSync: <T = unknown>() => T[];
  commonLen: () => Promise<number>;
  commonLenSync: () => number;
  commonIsEmpty: () => Promise<boolean>;
  commonIsEmptySync: () => boolean;
  commonAll: <T = unknown>() => Promise<Record<string, T>>;
  commonAllSync: <T = unknown>() => Record<string, T>;
}
