
[[release_projects]]
name = "rust"
path = "."
package_type = "cargo"

[[release_projects]]
name = "ui"
path = "ui"
package_type = "bun"

[[release_projects]]
name = "rust"
path = "ui/src-tauri"
package_type = "tauri-toml"


# install command
[[commands]]
name = "install"
description = "install"

[[commands.cmds]]
cmd = "bun"
args = ["install"]
run_dir = "./ui"


# dev command
[[commands]]
name = "dev"
description = "Run the application in development mode"

[[commands.cmds]]
cmd = "cargo"
args = ["tauri", "dev"]
run_dir = "."
always_run = true


# dev:android command
[[commands]]
name = "dev:android"
description = "Run the application in development mode on Android"

[[commands.cmds]]
cmd = "bun"
args = ["run", "build:android"]
run_dir = "ui/rust"

[[commands.cmds]]
cmd = "bun"
args = ["android"]
run_dir = "ui"
always_run = true


# dev:ios command
[[commands]]
name = "dev:ios"
description = "Run the application in development mode on iOS"

[[commands.cmds]]
cmd = "bun"
args = ["run", "build:ios"]
run_dir = "ui/rust"

[[commands.cmds]]
cmd = "bun"
args = ["ios"]
run_dir = "ui"
always_run = true


# build command
[[commands]]
name = "build"
description = "Build the application"

[[commands.cmds]]
cmd = "cargo"
args = ["tauri", "build"]
run_dir = "."


# build:win command
[[commands]]
name = "build:win"
description = "Build the application for Windows"

[[commands.cmds]]
cmd = "cargo"
args = ["tauri", "build", "--target", "x86_64-pc-windows-msvc"]
run_dir = "."


# build:mac:x64 command
[[commands]]
name = "build:mac:x64"
description = "Build the application for macOS x64"

[[commands.cmds]]
cmd = "cargo"
args = ["tauri", "build", "--target", "x86_64-apple-darwin"]
run_dir = "."


# build:mac:arm64 command
[[commands]]
name = "build:mac:arm64"
description = "Build the application for macOS arm64"

[[commands.cmds]]
cmd = "cargo"
args = ["tauri", "build", "--target", "aarch64-apple-darwin"]
run_dir = "."


# build:linux command
[[commands]]
name = "build:linux"
description = "Build the application for Linux"

[[commands.cmds]]
cmd = "cargo"
args = ["tauri", "build", "--target", "x86_64-unknown-linux-gnu"]
run_dir = "."


# build:android command
[[commands]]
name = "build:android"
description = "Build the application for Android"

[[commands.cmds]]
cmd = "bun"
args = ["n:prebuild:android:prod"]
run_dir = "ui"

[[commands.cmds]]
cmd = "bun"
args = ["run", "build:android"]
run_dir = "ui/rust"

[[commands.cmds]]
cmd = "bun"
args = ["build:android"]
run_dir = "ui"


# build:ios command
[[commands]]
name = "build:ios"
description = "Build the application for iOS"

[[commands.cmds]]
cmd = "bun"
args = ["n:prebuild:ios:prod"]
run_dir = "ui"

[[commands.cmds]]
cmd = "bun"
args = ["run", "build:ios"]
run_dir = "ui/rust"

[[commands.cmds]]
cmd = "bun"
args = ["build:ios"]
run_dir = "ui"


# prebuild:android command
[[commands]]
name = "prebuild:android"
description = "Prebuild the application for Android"

[[commands.cmds]]
cmd = "bun"
args = ["n:prebuild:android"]
run_dir = "ui"


# prebuild:ios command
[[commands]]
name = "prebuild:ios"
description = "Prebuild the application for iOS"

[[commands.cmds]]
cmd = "bun"
args = ["n:prebuild:ios"]
run_dir = "ui"


# prebuild:android:prod command
[[commands]]
name = "prebuild:android:prod"
description = "Prebuild the application for Android"

[[commands.cmds]]
cmd = "bun"
args = ["n:prebuild:android:prod"]
run_dir = "ui"


# prebuild:ios:prod command
[[commands]]
name = "prebuild:ios:prod"
description = "Prebuild the application for iOS"

[[commands.cmds]]
cmd = "bun"
args = ["n:prebuild:ios:prod"]
run_dir = "ui"


# clean:prebuild:android command
[[commands]]
name = "clean:prebuild:android"
description = "Clean the prebuild for Android"

[[commands.cmds]]
cmd = "bun"
args = ["clean:prebuild:android"]
run_dir = "ui"


# clean:prebuild:ios command
[[commands]]
name = "clean:prebuild:ios"
description = "Clean the prebuild for iOS"

[[commands.cmds]]
cmd = "bun"
args = ["clean:prebuild:ios"]
run_dir = "ui"


# clean:prebuild:android:prod command
[[commands]]
name = "clean:prebuild:android:prod"
description = "Clean the prebuild for Android"

[[commands.cmds]]
cmd = "bun"
args = ["clean:prebuild:android:prod"]
run_dir = "ui"


# clean:prebuild:ios:prod command
[[commands]]
name = "clean:prebuild:ios:prod"
description = "Clean the prebuild for iOS"

[[commands.cmds]]
cmd = "bun"
args = ["clean:prebuild:ios:prod"]
run_dir = "ui"


# build:module:android command
[[commands]]
name = "build:module:android"
description = "Build Android Module"

[[commands.cmds]]
cmd = "bun"
args = ["run", "build:android"]
run_dir = "ui/rust"


# build:module:ios command
[[commands]]
name = "build:module:ios"
description = "Build iOS Module"

[[commands.cmds]]
cmd = "bun"
args = ["run", "build:ios"]
run_dir = "ui/rust"


# icon command
[[commands]]
name = "icon"
description = "Generate Icon"

[[commands.cmds]]
cmd = "cargo"
args = [
  "run",
  "--manifest-path=cli/Cargo.toml",
  "--release",
  "--package",
  "icon-gen",
]
