
[[release_projects]]
name = "ui"
path = "ui"
package_type = "npm"

[[release_projects]]
name = "rust"
path = "."
package_type = "cargo"


# install command
[[commands]]
name = "install"
description = "Install the application"

[[commands.cmds]]
cmd = "pnpm"
args = ["install"]
run_dir = "ui"


# dev command
[[commands]]
name = "dev"
description = "Run the application in development mode"

[[commands.cmds]]
cmd = "pnpm"
args = ["dev"]
run_dir = "ui"
always_run = true


# build command
[[commands]]
name = "build"
description = "Build the application for Windows"

[[commands.cmds]]
cmd = "pnpm"
args = ["build"]
run_dir = "ui"


# build:android command
[[commands]]
name = "build:android"
description = "Build the application for Android"

[[commands.cmds]]
cmd = "pnpm"
args = ["build-android"]
run_dir = "ui"


# build:ios command
[[commands]]
name = "build:ios"
description = "Build the application for iOS"

[[commands.cmds]]
cmd = "pnpm"
args = ["build-ios"]
run_dir = "ui"


# icon command
[[commands]]
name = "icon"
description = "Generate Icon"

[[commands.cmds]]
cmd = "cargo"
args = [
    "run",
    "--manifest-path=cli/Cargo.toml",
    "--release",
    "--package",
    "icon-gen",
]
