// Auto generated by Craby. DO NOT EDIT.
#include "CxxLonanoteUiCoreModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace lonanoteuicore {
namespace modules {

std::string CxxLonanoteUiCoreModule::dataPath = std::string();

CxxLonanoteUiCoreModule::CxxLonanoteUiCoreModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxLonanoteUiCoreModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::lonanoteuicore::bridging::LonanoteUiCore>(
    craby::lonanoteuicore::bridging::createLonanoteUiCore(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::lonanoteuicore::bridging::LonanoteUiCore *ptr) { rust::Box<craby::lonanoteuicore::bridging::LonanoteUiCore>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::lonanoteuicore::utils::ThreadPool>(10);
  methodMap_["add"] = MethodMetadata{2, &CxxLonanoteUiCoreModule::add};
  methodMap_["divide"] = MethodMetadata{2, &CxxLonanoteUiCoreModule::divide};
  methodMap_["multiply"] = MethodMetadata{2, &CxxLonanoteUiCoreModule::multiply};
  methodMap_["subtract"] = MethodMetadata{2, &CxxLonanoteUiCoreModule::subtract};
}

CxxLonanoteUiCoreModule::~CxxLonanoteUiCoreModule() {
  invalidate();
}

void CxxLonanoteUiCoreModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxLonanoteUiCoreModule::add(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteUiCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoteuicore::bridging::add(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoteuicore::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteUiCoreModule::divide(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteUiCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoteuicore::bridging::divide(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoteuicore::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteUiCoreModule::multiply(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteUiCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoteuicore::bridging::multiply(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoteuicore::utils::errorMessage(err));
  }
}

jsi::Value CxxLonanoteUiCoreModule::subtract(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxLonanoteUiCoreModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0 = react::bridging::fromJs<double>(rt, args[0], callInvoker);
    auto arg1 = react::bridging::fromJs<double>(rt, args[1], callInvoker);
    auto ret = craby::lonanoteuicore::bridging::subtract(*it_, arg0, arg1);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::lonanoteuicore::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace lonanoteuicore
} // namespace craby
